INSERT INTO fields (
  key,
  label,
  section,
  field_type,
  unit,
  enum_options,
  has_default,
  default_value,
  display_order,
  created_at,
  updated_at
)
VALUES
  ('geral_potencia_nominal_requerida_kva', 'Potencia nominal requerida', 'Dados Gerais', 'number', 'kVA', NULL, FALSE, NULL, 0, NOW(), NOW()),
  ('geral_potencia_nominal_requerida_kw', 'Potencia nominal requerida', 'Dados Gerais', 'number', 'kW', NULL, FALSE, NULL, 1, NOW(), NOW()),
  ('geral_fator_potencia_requerido', 'Fator de potencia requerido', 'Dados Gerais', 'number', 'fp', NULL, TRUE, '0.8'::jsonb, 2, NOW(), NOW()),
  ('geral_topologia_aterramento', 'Topologia de aterramento', 'Dados Gerais', 'enum', NULL, '["TT","TN","IT"]'::jsonb, FALSE, NULL, 3, NOW(), NOW()),
  ('geral_ruido_audivel_maximo', 'Ruido audivel maximo', 'Dados Gerais', 'number', 'dBA', NULL, TRUE, '78'::jsonb, 4, NOW(), NOW()),
  ('geral_grau_protecao', 'Grau de protecao', 'Dados Gerais', 'text', NULL, NULL, TRUE, '"IP21"'::jsonb, 5, NOW(), NOW()),
  ('geral_pressao_minima_ar_ambiente', 'Pressao minima do ar ambiente permitida', 'Dados Gerais', 'number', 'kPa', NULL, TRUE, '70'::jsonb, 6, NOW(), NOW()),

  ('ambiental_elevacao_maxima', 'Elevacao maxima', 'Condicoes Ambientais', 'number', 'metros', NULL, TRUE, '1000'::jsonb, 1007, NOW(), NOW()),
  ('ambiental_umidade_relativa', 'Umidade relativa', 'Condicoes Ambientais', 'number', '%', NULL, TRUE, '95'::jsonb, 1008, NOW(), NOW()),
  ('ambiental_h2s_concentracao_salina', 'H2S e concentracao salina', 'Condicoes Ambientais', 'number', 'ppm', NULL, TRUE, '2'::jsonb, 1009, NOW(), NOW()),
  ('ambiental_temperatura_maxima_operacao', 'Temperatura maxima de operacao', 'Condicoes Ambientais', 'number', 'C', NULL, TRUE, '40'::jsonb, 1010, NOW(), NOW()),
  ('ambiental_grau_poluicao', 'Grau de poluicao', 'Condicoes Ambientais', 'text', NULL, NULL, TRUE, '"PD2"'::jsonb, 1011, NOW(), NOW()),

  ('retificador_tensao_nominal', 'Tensao nominal', 'AC Entrada Retificador', 'number', 'volts', NULL, FALSE, NULL, 2012, NOW(), NOW()),
  ('retificador_numero_fases', 'Numero de fases', 'AC Entrada Retificador', 'enum', NULL, '["2Ph","3Ph","3PhN"]'::jsonb, TRUE, '"3PhN"'::jsonb, 2013, NOW(), NOW()),
  ('retificador_frequencia_nominal', 'Frequencia nominal', 'AC Entrada Retificador', 'number', 'Hz', NULL, FALSE, NULL, 2014, NOW(), NOW()),
  ('retificador_transformador_isolador', 'Transformador isolador', 'AC Entrada Retificador', 'boolean', NULL, NULL, TRUE, 'true'::jsonb, 2015, NOW(), NOW()),
  ('retificador_tipo_retificador', 'Tipo de retificador', 'AC Entrada Retificador', 'enum', NULL, '["6 Pulsos","12 Pulsos","PFC"]'::jsonb, FALSE, NULL, 2016, NOW(), NOW()),
  ('retificador_disjuntor_entrada', 'Disjuntor de entrada', 'AC Entrada Retificador', 'boolean', NULL, NULL, TRUE, 'false'::jsonb, 2017, NOW(), NOW()),
  ('retificador_maximo_harmonico_entrada', 'Maximo harmonico de entrada', 'AC Entrada Retificador', 'number', '%', NULL, TRUE, '5'::jsonb, 2018, NOW(), NOW()),
  ('retificador_filtro_harmonicos_entrada', 'Filtro de harmonicos de entrada', 'AC Entrada Retificador', 'boolean', NULL, NULL, TRUE, 'false'::jsonb, 2019, NOW(), NOW()),
  ('retificador_faixa_tolerancia_tensao_entrada', 'Faixa de tolerancia de tensao de entrada', 'AC Entrada Retificador', 'number', '%', NULL, TRUE, '10'::jsonb, 2020, NOW(), NOW()),
  ('retificador_faixa_tolerancia_frequencia_entrada', 'Faixa de tolerancia de frequencia de entrada', 'AC Entrada Retificador', 'number', '%', NULL, TRUE, '2'::jsonb, 2021, NOW(), NOW()),

  ('bypass_tensao_nominal', 'Tensao nominal', 'AC Bypass', 'number', 'volts', NULL, FALSE, NULL, 3022, NOW(), NOW()),
  ('bypass_numero_fases', 'Numero de fases', 'AC Bypass', 'enum', NULL, '["2Ph","3Ph","3PhN"]'::jsonb, TRUE, '"3PhN"'::jsonb, 3023, NOW(), NOW()),
  ('bypass_frequencia_nominal', 'Frequencia nominal', 'AC Bypass', 'number', 'Hz', NULL, FALSE, NULL, 3024, NOW(), NOW()),
  ('bypass_transformador_isolador', 'Transformador isolador', 'AC Bypass', 'boolean', NULL, NULL, TRUE, 'true'::jsonb, 3025, NOW(), NOW()),
  ('bypass_disjuntor_entrada', 'Disjuntor de entrada', 'AC Bypass', 'boolean', NULL, NULL, TRUE, 'false'::jsonb, 3026, NOW(), NOW()),
  ('bypass_regulador_tensao', 'Regulador de tensao', 'AC Bypass', 'boolean', NULL, NULL, TRUE, 'false'::jsonb, 3027, NOW(), NOW()),
  ('bypass_faixa_tolerancia_tensao_entrada', 'Faixa de tolerancia de tensao de entrada', 'AC Bypass', 'number', '%', NULL, TRUE, '10'::jsonb, 3028, NOW(), NOW()),
  ('bypass_faixa_tolerancia_frequencia_entrada', 'Faixa de tolerancia de frequencia de entrada', 'AC Bypass', 'number', '%', NULL, TRUE, '2'::jsonb, 3029, NOW(), NOW()),
  ('bypass_mecanico_requerido', 'Bypass mecanico requerido', 'AC Bypass', 'boolean', NULL, NULL, TRUE, 'true'::jsonb, 3030, NOW(), NOW()),

  ('saida_tensao_nominal', 'Tensao nominal', 'Saida AC', 'number', 'volts', NULL, FALSE, NULL, 4031, NOW(), NOW()),
  ('saida_numero_fases', 'Numero de fases', 'Saida AC', 'enum', NULL, '["2Ph","3Ph","3PhN"]'::jsonb, TRUE, '"3PhN"'::jsonb, 4032, NOW(), NOW()),
  ('saida_frequencia_nominal', 'Frequencia nominal', 'Saida AC', 'number', 'Hz', NULL, FALSE, NULL, 4033, NOW(), NOW()),
  ('saida_transformador_isolador', 'Transformador isolador', 'Saida AC', 'boolean', NULL, NULL, TRUE, 'true'::jsonb, 4034, NOW(), NOW()),
  ('saida_chave_isolamento_saida', 'Chave de isolamento de saida', 'Saida AC', 'boolean', NULL, NULL, TRUE, 'true'::jsonb, 4035, NOW(), NOW()),
  ('saida_tolerancia_tensao_saida_carga_total', 'Tolerancia de tensao de saida em carga total', 'Saida AC', 'number', '%', NULL, TRUE, '1'::jsonb, 4036, NOW(), NOW()),
  ('saida_fator_potencia_saida', 'Fator de potencia de saida', 'Saida AC', 'number', NULL, NULL, TRUE, '0.8'::jsonb, 4037, NOW(), NOW()),
  ('saida_desequilibrio_tensao_carga_100', 'Desequilibrio de tensao com 100% de desequilibrio de carga', 'Saida AC', 'number', '%', NULL, FALSE, NULL, 4038, NOW(), NOW()),

  ('bateria_tipo', 'Tipo de bateria', 'Armazenamento de Energia (Bateria)', 'enum', NULL, '["VRLA","NiCad","Vent","SMC"]'::jsonb, TRUE, '"VRLA"'::jsonb, 5039, NOW(), NOW()),
  ('bateria_autonomia_esperada', 'Autonomia esperada', 'Armazenamento de Energia (Bateria)', 'text', NULL, NULL, TRUE, '"2h"'::jsonb, 5040, NOW(), NOW()),
  ('bateria_vida_util_projeto', 'Vida util de projeto', 'Armazenamento de Energia (Bateria)', 'text', NULL, NULL, TRUE, '"5 anos"'::jsonb, 5041, NOW(), NOW()),
  ('bateria_fabricante_desejado', 'Fabricante desejado', 'Armazenamento de Energia (Bateria)', 'text', NULL, NULL, FALSE, NULL, 5042, NOW(), NOW()),

  ('desempenho_eficiencia_ac_ac_minima', 'Eficiencia AC/AC minima', 'Desempenho e Topologia', 'number', NULL, NULL, TRUE, '0.82'::jsonb, 6043, NOW(), NOW()),
  ('desempenho_classe', 'Classe de desempenho', 'Desempenho e Topologia', 'text', NULL, NULL, TRUE, '"VFI SS 111"'::jsonb, 6044, NOW(), NOW()),
  ('desempenho_configuracao', 'Configuracao', 'Desempenho e Topologia', 'enum', NULL, '["Single","Parallel","Redundant","Dual Bus","Bypass"]'::jsonb, FALSE, NULL, 6045, NOW(), NOW()),
  ('desempenho_topologia', 'Topologia', 'Desempenho e Topologia', 'enum', NULL, '["Double Conversion","Line-interactive","Standby"]'::jsonb, FALSE, NULL, 6046, NOW(), NOW())
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  section = EXCLUDED.section,
  field_type = EXCLUDED.field_type,
  unit = EXCLUDED.unit,
  enum_options = EXCLUDED.enum_options,
  has_default = EXCLUDED.has_default,
  default_value = EXCLUDED.default_value,
  display_order = EXCLUDED.display_order,
  updated_at = NOW();
