const SECTION_ORDER = [
  "General",
  "Performance, configuration and topology",
  "Operating conditions – Environmental",
  "Storage and transportation conditions – Environmental",
  "5.2 UPS input specification",
  "5.3 UPS output specification",
  "Bypass (as applicable)",
  "5.4.2 Energy storage device – Battery",
  "5.6 Communication circuits"
];

const FIELDS_SEED = [
  { key: "general_model", label: "Model", section: "General", fieldType: "text", unit: "Manufacturer designation" },
  { key: "general_rated_output_apparent_power", label: "Rated output apparent power", section: "General", fieldType: "number", unit: "VA" },
  { key: "general_rated_output_active_power", label: "Rated output active power", section: "General", fieldType: "number", unit: "W" },

  {
    key: "perf_classification",
    label: "Performance classification",
    section: "Performance, configuration and topology",
    fieldType: "enum",
    enumOptions: ["VFD BB CC", "VI BB CC", "VFI BB CC"]
  },
  { key: "perf_multiple_normal_mode", label: "Multiple normal mode UPS", section: "Performance, configuration and topology", fieldType: "boolean" },
  {
    key: "perf_input_dependency_characteristics",
    label: "If yes, applicable set of input dependency characteristics",
    section: "Performance, configuration and topology",
    fieldType: "enum",
    enumOptions: ["(VFD, VI, VFI)", "(VFD, VI)", "(VFD, VFI)", "(VI, VFI)", "(VFD)", "(VI)", "(VFI)"]
  },
  {
    key: "perf_configuration",
    label: "Configuration",
    section: "Performance, configuration and topology",
    fieldType: "enum",
    enumOptions: ["Single", "Parallel", "Redundant", "Dual bus", "Bypass"]
  },
  {
    key: "perf_topology",
    label: "Topology",
    section: "Performance, configuration and topology",
    fieldType: "enum",
    enumOptions: ["Double-conversion", "Line-interactive", "Standby"]
  },

  { key: "env_oper_dimensions_uninstalled", label: "Dimensions uninstalled (height x width x depth)", section: "Operating conditions – Environmental", fieldType: "dimension", unit: "H x W x D mm" },
  { key: "env_oper_mass_in_use", label: "Mass in use/installed (with energy storage device if integrated)", section: "Operating conditions – Environmental", fieldType: "number", unit: "kg" },
  { key: "env_oper_pollution_degree", label: "Pollution degree", section: "Operating conditions – Environmental", fieldType: "enum", enumOptions: ["PD1", "PD2", "PD3"], hasDefault: true, defaultValue: "PD2" },
  { key: "env_oper_ambient_temperature_range", label: "Ambient temperature range, operating", section: "Operating conditions – Environmental", fieldType: "text", unit: "C", hasDefault: true, defaultValue: "+15 C to +30 C" },
  { key: "env_oper_relative_humidity_range", label: "Relative humidity, ambient range, operating (non-condensing)", section: "Operating conditions – Environmental", fieldType: "text", unit: "%", hasDefault: true, defaultValue: "10 % to 75 %" },
  { key: "env_oper_altitude_without_derating", label: "Altitude, maximum operating (without output power derating)", section: "Operating conditions – Environmental", fieldType: "text", unit: "m", hasDefault: true, defaultValue: "sea-level to 1 000 m" },
  { key: "env_oper_altitude_with_derating", label: "Altitude, maximum operating (with output power derating)", section: "Operating conditions – Environmental", fieldType: "text", unit: "m", hasDefault: true, defaultValue: "3 000 m at 90 % power" },
  { key: "env_oper_other_unusual_operating_conditions", label: "Other unusual operating conditions", section: "Operating conditions – Environmental", fieldType: "enum", enumOptions: ["yes (details)", "no"] },
  { key: "env_oper_acoustic_noise_normal_mode", label: "Acoustic noise: A-sound pressure (LpA at 1 m) — in normal mode", section: "Operating conditions – Environmental", fieldType: "number", unit: "dB (20 uPa)" },
  { key: "env_oper_acoustic_noise_stored_energy_mode", label: "Acoustic noise: A-sound pressure (LpA at 1 m) — in stored energy mode", section: "Operating conditions – Environmental", fieldType: "number", unit: "dB (20 uPa)" },

  { key: "env_storage_ambient_temperature_range", label: "Ambient temperature range", section: "Storage and transportation conditions – Environmental", fieldType: "text", unit: "C", hasDefault: true, defaultValue: "-25 C to +55 C" },
  { key: "env_storage_relative_humidity_range", label: "Relative humidity, ambient range (non-condensing)", section: "Storage and transportation conditions – Environmental", fieldType: "text", unit: "%", hasDefault: true, defaultValue: "10 % to 95 %" },
  { key: "env_storage_altitude_max_permitted", label: "Altitude, maximum permitted", section: "Storage and transportation conditions – Environmental", fieldType: "number", unit: "m", hasDefault: true, defaultValue: 3000 },
  { key: "env_storage_min_ambient_air_pressure", label: "Ambient air pressure, minimum permitted", section: "Storage and transportation conditions – Environmental", fieldType: "number", unit: "kPa", hasDefault: true, defaultValue: 70 },
  { key: "env_storage_energy_storage_specific_conditions", label: "Energy storage device, specific storage or transportation conditions", section: "Storage and transportation conditions – Environmental", fieldType: "enum", enumOptions: ["yes (details)", "no"] },
  { key: "env_storage_other_unusual_conditions", label: "Other unusual storage and transportation conditions", section: "Storage and transportation conditions – Environmental", fieldType: "enum", enumOptions: ["yes (details)", "no"] },

  { key: "input_number_of_phases", label: "Number of phases", section: "5.2 UPS input specification", fieldType: "text" },
  { key: "input_neutral_requirements", label: "Neutral requirements", section: "5.2 UPS input specification", fieldType: "text" },
  { key: "input_rated_input_current", label: "Rated input current", section: "5.2 UPS input specification", fieldType: "number", unit: "A" },
  { key: "input_input_power_factor", label: "Input power factor", section: "5.2 UPS input specification", fieldType: "number" },
  { key: "input_inrush_current", label: "Inrush current", section: "5.2 UPS input specification", fieldType: "text", unit: "% / s" },
  { key: "input_maximum_input_current", label: "Maximum input current", section: "5.2 UPS input specification", fieldType: "number", unit: "A" },
  { key: "input_current_overload_capacity", label: "Input current at overload capacity (where applicable curve of current against time)", section: "5.2 UPS input specification", fieldType: "text", unit: "% / s" },
  { key: "input_thdi", label: "Total harmonic distortion of current", section: "5.2 UPS input specification", fieldType: "number", unit: "%" },
  { key: "input_min_short_circuit_power_ssc", label: "Minimum short-circuit power (Ssc) capacity required from the AC input power", section: "5.2 UPS input specification", fieldType: "number", unit: "VA" },
  { key: "input_earth_leakage_current", label: "Earth leakage current", section: "5.2 UPS input specification", fieldType: "text", unit: "mA", hasDefault: true, defaultValue: "< 3,5 mA" },
  { key: "input_ac_distribution_compatibility", label: "AC power distribution system compatibility", section: "5.2 UPS input specification", fieldType: "enum", enumOptions: ["TN", "TT", "IT"] },
  { key: "input_rated_input_voltage", label: "Rated input voltage", section: "5.2 UPS input specification", fieldType: "number", unit: "V" },
  { key: "input_voltage_tolerance_band", label: "Input voltage tolerance band (+%, -%)", section: "5.2 UPS input specification", fieldType: "text", hasDefault: true, defaultValue: "± 10 %" },
  { key: "input_rated_input_frequency", label: "Rated input frequency", section: "5.2 UPS input specification", fieldType: "number", unit: "Hz" },
  { key: "input_frequency_tolerance_band", label: "Input frequency tolerance band (+%, -%)", section: "5.2 UPS input specification", fieldType: "text", hasDefault: true, defaultValue: "± 2 %" },
  { key: "input_compat_unusual_input_harmonic_voltage_distortion", label: "UPS compatibility with unusual input harmonic voltage distortion", section: "5.2 UPS input specification", fieldType: "enum", enumOptions: ["yes (details)", "no"] },
  { key: "input_compat_specific_input_protection_devices", label: "UPS compatibility with specific input supply protection devices", section: "5.2 UPS input specification", fieldType: "enum", enumOptions: ["yes (details)", "no"] },
  { key: "input_compat_all_pole_isolation", label: "UPS compatibility with all-pole isolation from the AC input power", section: "5.2 UPS input specification", fieldType: "boolean" },
  { key: "input_compat_standby_generator", label: "UPS compatibility with a specific standby generator", section: "5.2 UPS input specification", fieldType: "enum", enumOptions: ["yes (details)", "no"] },

  { key: "output_rated_output_voltage", label: "Rated output voltage", section: "5.3 UPS output specification", fieldType: "number", unit: "V" },
  { key: "output_rms_voltage_tolerance_band", label: "RMS output voltage tolerance band (+%, -%)", section: "5.3 UPS output specification", fieldType: "text" },
  { key: "output_rated_output_current", label: "Rated output current", section: "5.3 UPS output specification", fieldType: "number", unit: "A" },
  { key: "output_min_inverter_current_limit", label: "Minimum inverter current limit (ik1, ik2, ik3 as applicable) (% of rated/actual current and sustaining time)", section: "5.3 UPS output specification", fieldType: "text", unit: "% or A_RMS, s" },
  { key: "output_rated_frequency", label: "Rated frequency", section: "5.3 UPS output specification", fieldType: "number", unit: "Hz" },
  { key: "output_free_running_freq_tolerance_band", label: "Free-running output frequency tolerance band (non-synchronized) (+%, -%)", section: "5.3 UPS output specification", fieldType: "text" },
  { key: "output_sync_freq_tolerance_band", label: "Output frequency tolerance band accepted for synchronization with an external source (min to max)", section: "5.3 UPS output specification", fieldType: "text", unit: "Hz" },
  { key: "output_max_phase_angle_sync", label: "Maximum phase angle between the inverter and external source voltage waveforms", section: "5.3 UPS output specification", fieldType: "number", unit: "degrees" },
  { key: "output_rate_of_change_frequency", label: "Rate of change of the frequency (slew-rate) when synchronizing", section: "5.3 UPS output specification", fieldType: "number", unit: "Hz/s" },
  { key: "output_number_of_phases_available", label: "Number of phases available", section: "5.3 UPS output specification", fieldType: "text" },
  { key: "output_neutral_availability", label: "Neutral availability", section: "5.3 UPS output specification", fieldType: "boolean" },
  { key: "output_ac_distribution_compatibility", label: "AC power distribution system compatibility", section: "5.3 UPS output specification", fieldType: "enum", enumOptions: ["TN", "TT", "IT"] },
  { key: "output_thdv_normal_mode", label: "Total harmonic distortion of voltage — normal mode", section: "5.3 UPS output specification", fieldType: "number", unit: "%" },
  { key: "output_thdv_stored_energy_mode", label: "Total harmonic distortion of voltage — stored energy mode", section: "5.3 UPS output specification", fieldType: "number", unit: "%" },
  {
    key: "output_dynamic_output_performance_step_load",
    label: "Dynamic output performance following a step load application",
    section: "5.3 UPS output specification",
    fieldType: "enum",
    enumOptions: ["Dynamic output performance class 1", "Dynamic output performance class 2", "Dynamic output performance class 3"]
  },
  { key: "output_overload_capacity_normal_mode", label: "Overload capacity — normal mode", section: "5.3 UPS output specification", fieldType: "text", unit: "% / s" },
  { key: "output_overload_capacity_stored_energy_mode", label: "Overload capacity — stored energy mode", section: "5.3 UPS output specification", fieldType: "text", unit: "% / s" },
  { key: "output_overload_capacity_bypass_mode", label: "Overload capacity — bypass mode (see Bypass section)", section: "5.3 UPS output specification", fieldType: "text" },
  { key: "output_overload_rms_tolerance_affected", label: "RMS output voltage tolerance band affected (during overload)?", section: "5.3 UPS output specification", fieldType: "boolean" },
  { key: "output_overload_new_rms_tolerance_band", label: "If yes, new RMS output voltage tolerance band (+%, -%)", section: "5.3 UPS output specification", fieldType: "text" },
  { key: "output_fault_clearing_capacity_normal_mode", label: "Fault clearing capacity (max. protective device) — normal mode", section: "5.3 UPS output specification", fieldType: "text", unit: "A / trip curve / class / ms" },
  { key: "output_fault_clearing_capacity_stored_energy_mode", label: "Fault clearing capacity (max. protective device) — stored energy mode", section: "5.3 UPS output specification", fieldType: "text", unit: "A / trip curve / class / ms" },
  { key: "output_load_power_factor_rated_load", label: "Load power factor at rated load", section: "5.3 UPS output specification", fieldType: "text", hasDefault: true, defaultValue: "rated output active power / rated output apparent power" },
  { key: "output_pf_displacement_tolerance_band", label: "Permissible displacement power factor tolerance band of the load", section: "5.3 UPS output specification", fieldType: "text", unit: "% Lead to % Lag" },
  { key: "output_voltage_unbalance_100", label: "Voltage unbalance resulting from 100 % load unbalance ratio (polyphase UPS only)", section: "5.3 UPS output specification", fieldType: "number", unit: "%" },
  { key: "output_efficiency_100", label: "UPS efficiency in normal mode — Eff100%", section: "5.3 UPS output specification", fieldType: "number", unit: "%" },
  { key: "output_efficiency_75", label: "UPS efficiency in normal mode — Eff75%", section: "5.3 UPS output specification", fieldType: "number", unit: "%" },
  { key: "output_efficiency_50", label: "UPS efficiency in normal mode — Eff50%", section: "5.3 UPS output specification", fieldType: "number", unit: "%" },
  { key: "output_efficiency_25", label: "UPS efficiency in normal mode — Eff25%", section: "5.3 UPS output specification", fieldType: "number", unit: "%" },
  { key: "output_efficiency_no_load_mode", label: "UPS efficiency — EffN (no-load mode)", section: "5.3 UPS output specification", fieldType: "number", unit: "%" },
  { key: "output_no_load_losses", label: "No load losses", section: "5.3 UPS output specification", fieldType: "number", unit: "W" },
  { key: "output_parallel_redundant_failure_high_impedance", label: "Parallel redundant UPS failure — High impedance failure", section: "5.3 UPS output specification", fieldType: "text" },
  { key: "output_parallel_redundant_failure_low_impedance", label: "Parallel redundant UPS failure — Low impedance failure", section: "5.3 UPS output specification", fieldType: "text" },
  { key: "output_parallel_system_rated_active_power", label: "Rated output active power for a system consisting of two UPS operating in parallel (if applicable)", section: "5.3 UPS output specification", fieldType: "number", unit: "W" },
  { key: "output_parallel_system_rated_apparent_power", label: "Rated output apparent power for a system consisting of two UPS operating in parallel (if applicable)", section: "5.3 UPS output specification", fieldType: "number", unit: "VA" },

  { key: "bypass_maintenance_bypass_switch", label: "Maintenance bypass switch", section: "Bypass (as applicable)", fieldType: "enum", enumOptions: ["Internal", "External"] },
  { key: "bypass_automatic_bypass_switch", label: "Automatic bypass switch", section: "Bypass (as applicable)", fieldType: "enum", enumOptions: ["Static", "Electro-mechanical"] },
  { key: "bypass_transfer_time", label: "Bypass switch transfer time", section: "Bypass (as applicable)", fieldType: "enum", enumOptions: ["<= 0,1 ms", "<= 1,0 ms", "<= 10 ms", "> 10 ms"] },
  { key: "bypass_number_of_phases", label: "Number of phases", section: "Bypass (as applicable)", fieldType: "text" },
  { key: "bypass_neutral_requirements", label: "Neutral requirements", section: "Bypass (as applicable)", fieldType: "text" },
  { key: "bypass_rated_current", label: "Rated current", section: "Bypass (as applicable)", fieldType: "number", unit: "A" },
  { key: "bypass_overload_capacity", label: "Overload capacity (% of rated current and time duration)", section: "Bypass (as applicable)", fieldType: "text", unit: "% / s" },
  { key: "bypass_protective_device_rating", label: "Bypass protective device rating", section: "Bypass (as applicable)", fieldType: "text", unit: "A / trip curve" },
  { key: "bypass_earth_leakage_current", label: "Earth leakage current", section: "Bypass (as applicable)", fieldType: "text", unit: "mA", hasDefault: true, defaultValue: "< 3,5 mA" },
  { key: "bypass_power_factor", label: "Power factor", section: "Bypass (as applicable)", fieldType: "number" },
  { key: "bypass_min_short_circuit_power_ssc", label: "Minimum short-circuit power (Ssc) capacity required from the AC input power", section: "Bypass (as applicable)", fieldType: "number", unit: "VA" },
  { key: "bypass_ac_distribution_compatibility", label: "AC power distribution system compatibility", section: "Bypass (as applicable)", fieldType: "enum", enumOptions: ["TN", "TT", "IT"] },
  { key: "bypass_rated_voltage", label: "Rated voltage", section: "Bypass (as applicable)", fieldType: "number", unit: "V" },
  { key: "bypass_voltage_tolerance_band", label: "Voltage tolerance band (+%, -%)", section: "Bypass (as applicable)", fieldType: "text", hasDefault: true, defaultValue: "± 10 %" },
  { key: "bypass_rated_frequency", label: "Rated frequency", section: "Bypass (as applicable)", fieldType: "number", unit: "Hz" },
  { key: "bypass_frequency_tolerance_band", label: "Frequency tolerance band (+%, -%)", section: "Bypass (as applicable)", fieldType: "text", hasDefault: true, defaultValue: "± 2 %" },
  { key: "bypass_isolation_transformer", label: "Bypass isolation transformer", section: "Bypass (as applicable)", fieldType: "text", unit: "(details)" },
  { key: "bypass_inrush_current_if_transformer_inductor", label: "Inrush current (if transformer or inductor is supplied)", section: "Bypass (as applicable)", fieldType: "text", unit: "% / s" },

  { key: "bat_service_life", label: "Service life", section: "5.4.2 Energy storage device – Battery", fieldType: "number", unit: "years" },
  { key: "bat_quantity_blocks_cells_and_strings", label: "Quantity of blocks or cells and of parallel string strings if more than one", section: "5.4.2 Energy storage device – Battery", fieldType: "text" },
  { key: "bat_nominal_string_voltage", label: "Nominal string voltage", section: "5.4.2 Energy storage device – Battery", fieldType: "number", unit: "V DC" },
  { key: "bat_technology", label: "Battery technology", section: "5.4.2 Energy storage device – Battery", fieldType: "text", hasDefault: true, defaultValue: "Vented or valve-regulated lead-acid, NiCd, NiMH, Li-ion, etc." },
  { key: "bat_nominal_capacity_and_rate", label: "Nominal capacity of total battery and reference discharge rate (Cx rate)", section: "5.4.2 Energy storage device – Battery", fieldType: "text", unit: "Ah / Cx", hasDefault: true, defaultValue: "[C10] (suggested reference)" },
  { key: "bat_stored_energy_time_backup", label: "Stored energy time (back-up time at reference test load)", section: "5.4.2 Energy storage device – Battery", fieldType: "time", unit: "hh:mm" },
  { key: "bat_restored_energy_time_recharge_90", label: "Restored energy time (recharge time to 90 % capacity)", section: "5.4.2 Energy storage device – Battery", fieldType: "time", unit: "hh:mm" },
  { key: "bat_ambient_temperature_rated", label: "Ambient temperature at which battery performance is rated", section: "5.4.2 Energy storage device – Battery", fieldType: "number", unit: "C" },
  { key: "bat_dc_port_earth_condition", label: "Earth condition of DC port (remote battery only)", section: "5.4.2 Energy storage device – Battery", fieldType: "text", hasDefault: true, defaultValue: "(+), (-) or centre or Not earthed" },
  { key: "bat_dc_port_isolation", label: "Isolation of DC port from input and/or output (remote battery only)", section: "5.4.2 Energy storage device – Battery", fieldType: "text", hasDefault: true, defaultValue: "Referenced to input or output, or Isolated from input and output" },
  { key: "bat_ripple_current_normal_mode", label: "Battery ripple current during normal mode operation (if exceeding 5 % of Ah capacity)", section: "5.4.2 Energy storage device – Battery", fieldType: "text", hasDefault: true, defaultValue: "% of numerical Ah capacity [C10 discharge rate]" },
  { key: "bat_additional_characteristics_supplier", label: "Additional characteristics provided by the battery supplier for a remote battery", section: "5.4.2 Energy storage device – Battery", fieldType: "text" },
  { key: "bat_additional_or_unusual_conditions", label: "Additional or unusual conditions", section: "5.4.2 Energy storage device – Battery", fieldType: "text" },

  { key: "comm_ports_available", label: "Signal, control and communication ports available", section: "5.6 Communication circuits", fieldType: "text" }
];

module.exports = {
  SECTION_ORDER,
  FIELDS_SEED
};
